name: flutter_localization
description: Flutter Localization is a package use for in-app localization with map data. More easier and faster to implement and inspired by the flutter_localizations itself.
version: 0.1.10
homepage: https://github.com/channdara/flutter_localization

scripts:
  # rps test
  test: 'flutter pub publish --dry-run'
  # rps publish
  publish: 'flutter pub publish'

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: '>=1.12.13'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  plugin_platform_interface: ^2.1.3
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.mastertipsy.flutter_localization
        pluginClass: FlutterLocalizationPlugin
      ios:
        pluginClass: FlutterLocalizationPlugin
      web:
        pluginClass: FlutterLocalizationWeb
        fileName: flutter_localization_web.dart
      linux:
        pluginClass: FlutterLocalizationPlugin
      macos:
        pluginClass: FlutterLocalizationPlugin
      windows:
        pluginClass: FlutterLocalizationPluginCApi